version: "3"
services:
  postgres:
    image: postgres:15
    container_name: graphql-task-postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: graphql-task-pgadmin
    restart: unless-stopped
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
  redis:
    image: redis/redis-stack
    container_name: graphql-task-redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
      - ${REDISINSIGHT_PORT}:8001
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
  graphql-task:
    image: graphql-task-dev
    build:
      context: .
      target: graphql-task-dev
      args:
        - PORT:${PORT}
    container_name: graphql-task-dev
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/graphql-task/
volumes:
  postgres:
    name: graphql-task-postgres
  redis:
    name: graphql-task-redis
  pgadmin:
    name: graphql-task-pgadmin
networks:
  default:
    name: graphql-task
