version: "3"
services:
  postgres:
    image: postgres:15
    container_name: graphql-task-postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
 
volumes:
  postgres:
    name: graphql-task-postgres
networks:
  default:
    name: graphql-task
